name: LuckSMPS3
version: ${version}
main: pl.Main
api-version: "${mcVersion}"
commands:
  books:
    permission: op
  luck:
  withdraw:
  luckbook:
    permission: op
  trust:
  untrust:
  clearluck:
    permission: op
  setluckbook:
    permission: op
  luckstart:
    permission: op
  cooldown:
    permission: op