reroll_on_join: true
reroll_on_start: true
broadcast_obtaining_luck: true
started_smp: false
actionbar_cooldown: true
RawStrengthComboForAbility: 2
dark_sense_range: 20
WindManipulationMaceMinFallDistance: 5
AdrenalineRushHasteMax: 10
drop_reroll_on_death: true # if set to false it will drop the book instead of a reroller

chances:
  thundercharge: 20
  raw_strength: 35
  hellscorch1: 20
  hellscorch2: 15
  dark_sense: 50
  wind_manipulation1: 50
  wind_manipulation2: 45
  adrenaline_rush: 20
  adrenaline_rush_upgrade: 30

damage:
  thundercharge: 3
  raw_strength: 1.5 # the damage modifier
  hellscorch1: 1.3 # Damage modifier
  hellscorch2: 12
  dark_sense: 7
  wind_manipulation1: 2.5 # Damage per block fallen
  wind_manipulation2: 4

durations:
  thundercharge: 9
  raw_strength: 10
  wind_manipulation2: 2
  adrenaline_rush: 35

cooldowns:
  thundercharge: 35
  raw_strength: 0
  hellscorch1: 10
  hellscorch2: 60
  dark_sense: 25
  wind_manipulation1: 35
  wind_manipulation2: 35
  adrenaline_rush: 90