name: LuckSMPS3
version: 1.0 #pom.xml
main: pl.Main
api-version: '1.21'
commands:
  books:
    permission: op
  luck:
  withdraw:
  luckbook:
    permission: op
  trust:
  untrust:
  clearluck:
    permission: op
  setluckbook:
    permission: op
  luckstart:
    permission: op
  cooldown:
    permission: op